export const FIELD_LEVEL = 'FIELD_LEVEL'
export const FOLDER_LEVEL = 'FOLDER_LEVEL'
export const MODE_INITIAL_VALUE = 'FOLDER_LEVEL-OR-FIELD_LEVEL'
export const MODE_DATASOURCE_NAME = 'Mode-Of-Translation'
export const API_KEY_INITIAL_VALUE = 'Enter-Api-Key-Here'
export const API_KEY_DATASOURCE_NAME = 'Deepl-Api-key'